# Generated by Django 5.0.2 on 2024-02-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluma_app', '0004_alter_note_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
