# Generated by Django 5.0.2 on 2024-02-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pluma_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
