# Generated by Django 5.0.2 on 2024-02-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pluma_users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
