# Generated by Django 5.0.2 on 2024-02-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pluma_users", "0003_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
